### ISSUE TITLE
Unable to uninstall properly the plugin

### ISSUE THREAD

**Issue by abatista75** [iridakos/release_logs#12]
Here is the log:

```
Migrating release_logs (Release Logs plugin)...
== 7 RemoveUniqueuIndexFromReleaseLogEntries: reverting =======================
rake aborted!
An error has occurred, all later migrations canceled:



remove_index is only reversible if given a :column option.

/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration/command_recorder.rb:157:in `invert_remove_index'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration/command_recorder.rb:66:in `inverse_of'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration/command_recorder.rb:50:in `record'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration/command_recorder.rb:83:in `remove_index'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:652:in `method_missing'
/usr/share/redmine-3.0.1/plugins/release_logs/db/migrate/007_remove_uniqueu_index_from_release_log_entries.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:604:in `block in exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:493:in `block (2 levels) in revert'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration/command_recorder.rb:38:in `revert'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:493:in `block in revert'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:640:in `suppress_messages'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:492:in `revert'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:604:in `exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:588:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:765:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:952:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:827:in `down'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/migration.rb:802:in `migrate'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:474:in `migrate_plugin'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:446:in `migrate'
/usr/share/redmine-3.0.1/lib/redmine/plugin.rb:457:in `migrate'
/usr/share/redmine-3.0.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by iridakos** [comment]
Thanks for pointing this, I'll change the migration to support the reversed action.

**Comment by patrickmorin** [comment]
Hi, still present in the 1.0.0
