### ISSUE TITLE
undefined method `in_time_zone'

### ISSUE THREAD

**Issue by akuznecov** [iridakos/release_logs#41]
Hello,

Just got such error on release log "save & publish" procedure _when date and time are specified_ on **Release plan** section

```
NoMethodError (undefined method `in_time_zone' for Fri, 10 Jun 2016:Date):
  plugins/release_logs/app/controllers/release_logs_controller.rb:105:in `save_release_log'
  plugins/release_logs/app/controllers/release_logs_controller.rb:32:in `create'
  actionpack (3.2.22.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.22.2) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.22.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
```

Environment
Redmine: 2.6.10
Ruby: 2.2.3-p173
Rails: 3.2.22.2
Release logs plugin: master

What could be or should be done to avoid this problem?
Thanks in advance

**Comment by iridakos** [comment]
Hi @akuznecov and sorry for such a delayed response. Did you overcome your problem?
